### ISSUE TITLE
Hide sprite on sendback and silent (fly, dig)

### ISSUE THREAD

**Issue by MidwayMarshall** [MidwayMarshall/html#14]
Make sprite invisible when it shouldn't show

**Comment by coyotte508** [comment]
By the way I just added the event on the relay station, need first to restart it and then to add the events in the wbeclient as well.

**Comment by coyotte508** [comment]
https://github.com/po-devs/po-web/commit/d9e66cfb3221524b9465592766fb86095ea9345e

The triggers for `vanish` and `reappear` have been added.

**Comment by coyotte508** [comment]
I meant they have been added in the webclient, it's not done in teh animated window =x
