### ISSUE TITLE
Chinese pokemon names

### ISSUE THREAD

**Issue by coyotte508** [MidwayMarshall/html#7]
Show pokemon name in the battle window instead of their nicknames, or chinese people's windows are empty.

**Comment by coyotte508** [comment]
Actually could show nicknames as long as they have only valid characters.

**Comment by MidwayMarshall** [comment]
For future reference:
3,4 ♥  ♦
11-13,15 ♂, ♀, ♫, <sup>5-star</sup>
32-126 <sup>common symbols, numbers, letters</sup>
166,167 <sup>Pk</sup>,<sub>Mn</sub>
173 ¡
These char ids are mapped
175-184 (will display but these are mapped to alternate number style (the real health)
